name: Pods Updater

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: bidon-io/dependamachine/.github/workflows/ios-pods-updater.yml@main
    with:
      config_path: .github/pods-updater-config.json
      base_branch: develop
      reviewers: "bidon-io/bidon-ios"
      runner_labels: '["self-hosted", "macOS", "ARM64", "xcode-16", "bidon"]'
    secrets:
      APP_ID: ${{ secrets.PODS_UPDATER_APP_ID_V2 }}
      APP_PRIVATE_KEY: ${{ secrets.PODS_UPDATER_APP_PRIVATE_KEY_V2 }}
